### ISSUE TITLE
get some errors about mxnet

### ISSUE THREAD

**Issue by zzw1123** [chinakook/hr101_mxnet#2]
thanks for your attribute!!! it is very helpful for me!!
but after i type "python tiny_detection_mxnet.py" in the command window,i get some errors ,i cannot find the solution on internet.the errors are as follows:

[16:42:39] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:304: [16:42:39] src/c_api/c_api_ndarray.cc:392: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

Stack trace returned 10 entries:
[bt] (0) /home/zzw/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xc78bc) [0x7fabe50668bc]
[bt] (1) /home/zzw/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(MXImperativeInvoke+0xaca) [0x7fabe5c83f0a]
[bt] (2) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fabf1722e40]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7fabf17228ab]
[bt] (4) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7fabf19323df]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7fabf1936d82]
[bt] (6) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (7) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (8) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (9) python(PyEval_EvalFrameEx+0x68d1) [0x4ca8d1]

Traceback (most recent call last):
  File "tiny_detection_mxnet.py", line 116, in <module>
    mod.bind(for_training=False, data_shapes=[('data', (1, 3, 224, 224))], label_shapes=None, force_rebind=False)
  File "/home/zzw/.local/lib/python2.7/site-packages/mxnet/module/module.py", line 388, in bind
    state_names=self._state_names)
  File "/home/zzw/.local/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 216, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/zzw/.local/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 312, in bind_exec
    shared_group))
  File "/home/zzw/.local/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 632, in _bind_ith_exec
    context, self.logger)
  File "/home/zzw/.local/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 610, in _get_or_reshape
    arg_arr = nd.zeros(arg_shape, context, dtype=arg_type)
  File "/home/zzw/.local/lib/python2.7/site-packages/mxnet/ndarray.py", line 1003, in zeros
    return _internal._zeros(shape=shape, ctx=ctx, dtype=dtype)
  File "<string>", line 15, in _zeros
  File "/home/zzw/.local/lib/python2.7/site-packages/mxnet/_ctypes/ndarray.py", line 72, in _imperative_invoke
    c_array(ctypes.c_char_p, [c_str(str(val)) for val in vals])))
  File "/home/zzw/.local/lib/python2.7/site-packages/mxnet/base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:42:39] src/c_api/c_api_ndarray.cc:392: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

Stack trace returned 10 entries:
[bt] (0) /home/zzw/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xc78bc) [0x7fabe50668bc]
[bt] (1) /home/zzw/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(MXImperativeInvoke+0xaca) [0x7fabe5c83f0a]
[bt] (2) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fabf1722e40]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7fabf17228ab]
[bt] (4) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7fabf19323df]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7fabf1936d82]
[bt] (6) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (7) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (8) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (9) python(PyEval_EvalFrameEx+0x68d1) [0x4ca8d1]

i think it can be something wrong about my mxnet,can you help me??thanks again!

**Comment by zzw1123** [comment]
i wrongly installed the mxnet of cpu version ...
now i uninstalled it ,and install the gpu version again,the error disappears...
