### ISSUE TITLE
when running the code  I got this error. and stuck what to do? 

### ISSUE THREAD

**Issue by Abd2z** [chinakook/hr101_mxnet#9]
The following  is the error I got:
D:\teny\hr101_mxnet>python tiny_detection_mxnet.py
[20:12:48] C:\projects\mxnet-distro-win\mxnet-build\dmlc-core\include\dmlc/logging.h:308: [20:12:48] C:\projects\mxnet-distro-win\mxnet-build\src\storage\storage.cc:118: Compile with USE_CUDA=1 to enable GPU usage
Traceback (most recent call last):
  File "C:\Users\user1\Downloads\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mxnet\symbol\symbol.py", line 1488, in simple_bind
    ctypes.byref(exe_handle)))
  File "C:\Users\user1\Downloads\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mxnet\base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:12:48] C:\projects\mxnet-distro-win\mxnet-build\src\storage\storage.cc:118: Compile with USE_CUDA=1 to enable GPU usage

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tiny_detection_mxnet.py", line 106, in <module>
    mod.bind(for_training=False, data_shapes=[('data', (1, 3, 224, 224))], label_shapes=None, force_rebind=False)
  File "C:\Users\user1\Downloads\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mxnet\module\module.py", line 428, in bind
    state_names=self._state_names)
  File "C:\Users\user1\Downloads\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mxnet\module\executor_group.py", line 237, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "C:\Users\user1\Downloads\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mxnet\module\executor_group.py", line 333, in bind_exec
    shared_group))
  File "C:\Users\user1\Downloads\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mxnet\module\executor_group.py", line 611, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "C:\Users\user1\Downloads\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mxnet\symbol\symbol.py", line 1494, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (1, 3, 224, 224)
[20:12:48] C:\projects\mxnet-distro-win\mxnet-build\src\storage\storage.cc:118: Compile with USE_CUDA=1 to enable GPU usage

**Comment by chinakook** [comment]
Because your mxnet version is not compiled with CUDA, but the detector use that.
You can change 'context=mx.gpu()' to 'context=mx.cpu()' in line 100 of tiny_detection_mxnet.py to detect with CPU.
